In [ ]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5], [1,2,3,4,5]])
arr3 = np.array([[[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]]])

print(arr1, type(arr1), arr1.ndim)
print(arr2, type(arr2), arr2.ndim)
print(arr3, type(arr3), arr3.ndim)

[1 2 3 4 5] <class 'numpy.ndarray'> 1
[[1 2 3 4 5]
 [1 2 3 4 5]] <class 'numpy.ndarray'> 2
[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]] <class 'numpy.ndarray'> 3


In [ ]:
#  indexing dalam ndarray
import numpy as np

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5], [9,2,3,4,5]])
arr3 = np.array([[[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]]])

#array 1 dimensi menampilkan data kedua yaitu index 1
print(arr1[1])
#array 2 dimensi mengambil baris kedua, kolom pertama
print(arr2[1, 0])
#array 3 dimensi mengambil baris kedua kolom pertama
print(arr3[0,1,2])

2
9
8


In [ ]:
# slicing array

import numpy as np

arr1 = np.array([1,2,3,4,5,6,7,8,9])
arr2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

#slicing 1 dimensi
# dari index ke 1 sampai 4
print(arr1[1:5])
# dari awal sampai index ke 2
print(arr1[:3])
# dari index ke 3 sampai akhir
print(arr1[3:])
# dari index ke 2 sampai 4 dengan 2 step
print(arr1[1:5:2])

print("---------------")

# slicing 2 dimensi
# array kedua, index 1 sampai 3
print(arr2[1, 1:4])
# array pertama dan kedua untuk setiap array index ke 2
print(arr2[0:2, 2])

[7 8 9]
[3 8]


In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])

str_arr = arr.astype(str)
print(str_arr, str_arr.dtype)

fl_arr = arr.astype('f')
print(fl_arr, fl_arr.dtype)

['1' '2' '3' '4' '5'] <U21
[1. 2. 3. 4. 5.] float32


In [ ]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5], [1,2,3,4,5]])
arr3 = np.array([[[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]]])

print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(5,)
(2, 5)
(1, 3, 5)


In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr2 = np.array([[1,2,3,4,5], [1,2,3,4,5]])
arr3 = np.array([[[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]]])
# mengubah array 1 dimensi jadi 2 dimensi
print(arr1.reshape(3,4))
# membuat array 2 dimensi jadi 1 dimensi (flatenning)
print(arr2.reshape(-1))
# membuat array 1 dimensi jadi 3 dimensi
print(arr1.reshape(2,3,2))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4 5 1 2 3 4 5]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
# iterasi pada ndarray
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5], [1,2,3,4,5]])

# iterasi pada ndarray 1 dimensi
for x in arr1:
  print(x)

# iterasi pada ndarray 2 dimensi
for x in arr2:
  for y in x:
    print(y, end=', ')
  print('')

1
2
3
4
5
1, 2, 3, 4, 5, 
1, 2, 3, 4, 5, 


In [ ]:
import numpy as np

arr1 = np.array([[1,2,3,4,5]])
arr2 = np.array([[6,7,8,9,10]])

arr = np.concatenate((arr1, arr2), axis=0)
arr_flat = np.concatenate((arr1, arr2), axis=1)

print(arr)
print(arr_flat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5  6  7  8  9 10]]


In [ ]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array_split(arr1,3)


print(arr2)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
import numpy as np

arr1 = np.array([[1,2,3,4,5,6], [1,2,3,4,6,6]])

x = np.where(arr1 == 6)

print(x)

(array([0, 1, 1]), array([5, 4, 5]))


In [ ]:
import numpy as np

arr = np.array(["Aliif", "arief", "Maulana"])

print(np.sort(arr))

['Aliif' 'Maulana' 'arief']


In [1]:
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[9 5 3 7 5]
 [5 9 5 3 9]
 [7 5 9 7 9]]
